var path=require('path');
var webpack=require('webpack');
var VueLoaderPlugin=require('vue-loader/lib/plugin');

module.exports={
	entry:['@babel/polyfill','./src/main.js'],
	output:{
		path:path.resolve(__dirname,'./dist'),
		filename:'bundle.js'
	},
	mode:'development',
	devServer:{
		historyApiFallback:true,
		overlay:true
	},
	resolve:{
		alias:{
			'vue$':'vue/dist/vue.esm.js',
			'@':path.resolve(__dirname,'./src')
		},
		extensions:['.js','.vue','.json']
	},
	module:{
		rules:[
			//CSS
			{
				test:/\.css$/,
				use:[
					'vue-style-loader',
					'css-loader'
				]
		  },
			{
				test:/\.scss$/,
				use:[
					'vue-style-loader',
					'css-loader',
					'sass-loader'
				]
			},
			{
				test:/\.sass$/,
				use:[
					'vue-style-loader',
					'css-loader',
					'sass-loader?indentedSyntax'
				]
			},
			//图片
			{
				test:/\.(png|jpg|svg|gif)$/,
				use:[
					{
						loader:'file-loader',
						options:{
							name:'[name].[ext]?[hash]'
						}
					}
				]
			},
			//babel
			{
				test:/\.js$/,
				exclude:/node_modules/,
				loader:'babel-loader'
			},
			{
				test:/\.vue$/,
				loader:'vue-loader'
			},
			//url-loader
			{
				test:/\.(woff|svg|eot|ttf|woff2)\??.*$/,
				loader:'url-loader?name=fonts/[name].[md5:hash:hex:7].[ext]'
			}
		]
	},
	plugins:[
		new VueLoaderPlugin()
	]
}